import React, { ChangeEvent, ReactNode } from 'react';
import './style.scss';
import { TreeNodeType } from './TreeNode';
export declare type TreeData = TreeNodeType[];
export declare type TreeProps = {
    treeData: TreeNodeType[];
    checkedKeys?: string[];
    defaultCheckedKeys?: string[];
    defaultExpandKeys?: string[];
    defaultSelectedKeys?: string[];
    expandKeys?: string[];
    selectedKeys?: string[];
    multiple?: boolean;
    checkable: boolean;
    autoExpandParent?: boolean;
    onCheck?: (newCheckedKeys: string[], checkNode: TreeNodeType, event: ChangeEvent<HTMLInputElement>) => void;
    onExpand?: (expandKeys: string[], expandNode: TreeNodeType) => void;
    onSelect?: (selectedKeys: string[], selectNode: TreeNodeType) => void;
    expandIcon?: ReactNode;
    collapseIcon?: ReactNode;
    loadData?: (node: TreeNodeType) => Promise<any>;
};
declare const Tree: React.FC<TreeProps>;
export default Tree;
